Controllers/ActivityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyAdventure.Controllers
{
    public class ActivityController : Controller
    {
        // GET: Activity
        public ActionResult Index()
        {
            return View();
        }
       
        public ActionResult Details()
        {
            return View();
        }


     
        public ActionResult Create(string param1)
        {
            string x = "";

            return View();

        }




    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyAdventure.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Views/Activity/Create.cshtml
@{
    ViewBag.Title = "New Activity";
}

<h2>New Activity</h2>

<div class="row">
    @*<div class="col-md-12">
        </div>*@

    <div class="row">
        <div class="col-lg-5">
            <div class="input-group mb-3">

                <form class="form-inline">

                    <div class="panel panel-title">
                        <div class="panel-body">

                            <div class="row">
                                <div class="col-lg-12">
                                    <label for="fname">Activity Name</label>
                                </div>
                                <div class="col-sm-12">
                                    <input type="text" class="form-control" id="inputPassword2" maxlength="250">
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-lg-12">
                                    <label for="fname">Date : </label>
                                </div>
                                <div class="container">
                                    <div class="row">
                                        <div class='col-sm-6'>
                                            <div class="form-group">
                                                <div class='input-group date' id='datetimepicker1'>
                                                    <input type='text' class="form-control" />
                                                    <span class="input-group-addon">
                                                        <span class="glyphicon glyphicon-calendar"></span>
                                                    </span>
                                                    <script type="text/javascript">
                                                        $(function () {
                                                            $('#datetimepicker1').datetimepicker();
                                                        });
                                                    </script>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-lg-12">
                                    <label for="fname">Address : </label>
                                </div>
                                <div class="col-lg-12">
                                    <input type="text" class="form-control" id="txtAddress">
                                </div>
                            </div>
                            </br>
                            <div class="row">
                                <div class="col-lg-12">
                                    <input type="submit" class="btn btn-primary active" value="Save">
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

Views/Activity/Index.cshtml
<!DOCTYPE HTML>
<html>
<head>
    <meta charset="UTF-8">
    <title>Create Map Sample | Longdo Map</title>
    <style type="text/css">
        html {
            height: 100%;
            width: 100%;
            flex-direction: row;
        }

        body {
            margin: 0px;
            height: 100%;
            width: 100%;
            flex: 4;
        }

        #map {
            height: 100%;
            width: 100%;
        }

        #searchPlace {
            flex: 2;
        }

        #result {
            height: 400px;
            overflow-y: scroll;
        }

        #suggest {
            position: absolute;
            display: none;
            background-color: azure;
            border: 1px solid #000000;
            padding: 4px;
            flex-direction: column;
        }
    </style>
    <script type="text/javascript" src="https://api.longdo.com/map/?key=451c751a0e4183aea3747e94cf68f7d5">
    </script>
    <script>
        var map;
        var search;
        function init() {
            map = new longdo.Map({
                placeholder: document.getElementById('map'),

            });
            search = document.getElementById('search');
            map.Search.placeholder(
                document.getElementById('result')
            );
            //When user press an Enter button #search
            search.onkeyup = function (event) {
                if ((event || window.event).keyCode != 13)
                    return;
                doSearch();
            }
            search.oninput = function () {
                if (search.value.length < 3) {
                    suggest.style.display = 'none';
                    return;
                }

                map.Search.suggest(search.value, {
                    area: document.getElementById('area').value
                });
            };
        }
        function doSearch() {
            map.Search.search(search.value, {
                tag: document.getElementById('search').value,
            });
            suggest.style.display = 'none';
        }
    </script>
</head>
<body onload="init();">

    <div id="map"></div>
    </br>
    <div id="searchPlace">
        <input id="search" class="form-control col-lg-10" placeholder="Search" maxlength="250"></input>
        <input type="button"
        class="btn btn-secondary col-lg-1"
        value="New Activity"
        onclick="location.href='@Url.Action("Create", "Activity")'" />

        <div id="result">
            

        </div>
    </div>

</body>
</html>

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <!-- Image and text -->
    <div class="col-md-12">
        <div class="panel-group">
            <div class="panel panel-default">


                <div class="panel-heading">
                    <img src="~/Content/Image/25694.svg" width="30" height="30" class="d-inline-block align-top" loading="lazy"> My Activity

                </div>


            </div>

            <div class="panel panel-default">
                <div class="panel-body">
                    @RenderBody()
                </div>
            </div>
        </div>
    </div>
    <div class="container body-content">
        <hr />
        <footer style="text-align: center">
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>